name: project_servify
description: "A new Flutter project."
publish_to: 'none' 
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  
  firebase_core: ^3.6.0      
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1

  http: ^1.2.0
  googleapis_auth: ^1.6.0
  connectivity_plus: ^6.0.0
  image_picker: ^1.0.4
  crypto: ^3.0.3

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/servify_logo.png
   # - secrets/service_account.json